//layout.js
import { Geist, Geist_Mono, Roboto } from 'next/font/google';
import "./globals.css";
import Footer from "./HomeHub/Footer";  // Check path
import Header from "./HomeHub/Header"; // Import the new Header, adjust path


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    variable: '--font-roboto',
    display: 'swap',
});

export const metadata = {
    title: "Seensd",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable}`}>
            <body>
                <Header />
                <main className="pt-10"> {/* Add padding-top to prevent content overlap */}
                    {children}
                </main>

                <Footer />
            </body>
        </html>
    );
}