// app/layout.js

import { Geist, Geist_Mono, Roboto } from 'next/font/google';
import "./globals.css";
import Footer from "./HomeHub/Footer";
import Header from "./HomeHub/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata = {
  title: "Seensd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable}`}>
      <head>
        {/* Remove the Google Fonts <link> tags from here */}
      </head>
      <body className={`antialiased box-border w-full`}>
        <Header />
        <div className="mt-[-20px]"> 
        {/* 64px is a typical height for a fixed header, adjust as needed */}
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}