// app/layout.js
import { Geist, Geist_Mono, Roboto } from 'next/font/google'; // Import Roboto
import "./globals.css";
import Footer from "./HomeHub/Footer";
import Header from "./HomeHub/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({ // Load Roboto using next/font
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto', // Optional: Define a CSS variable for Roboto
  display: 'swap', // Recommended
});


export const metadata = {
  title: "Seensd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable}`}>
      {/* Add roboto.variable to the className */}
      <head>
        {/* Remove the Google Fonts <link> tags from here */}
      </head>
      <body
        className={`antialiased box-border w-full`} // Moved font classes to body tag
      >
        <Header />
        <div style={{ paddingTop: "55px" }}></div>
        {children}
        <Footer />
      </body>
    </html>
  );
}